const API_TYPE = {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  CHECK_AUTH: "CHECK_AUTH",

  GET_POSTS: "GET_POSTS",
  GET_POST: "GET_POST",
  POST_POST: "POST_POST",
  PUT_POST: "PUT_POST",
  DELETE_POST: "DELETE_POST",

  GET_COMMENTS: "GET_COMMENTS",
  GET_COMMENT: "GET_COMMENT",
  POST_COMMENT: "POST_COMMENTS",
  PUT_COMMENT: "PUT_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
};
export default API_TYPE;
